---
abstract: 'OAI-PMH provider backed by a searchable Catmandu::Store'
author:
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
build_requires:
  Software::License: 0
  Test::Exception: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-Catmandu-OAI
provides:
  Dancer::Plugin::Catmandu::OAI:
    file: lib/Dancer/Plugin/Catmandu/OAI.pm
    version: 0.0302
requires:
  Catmandu: 0.03
  Dancer: 1.3
  DateTime: 0
  perl: v5.10.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.0302
